[package]
name = "store-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["totoroyyw <totoro@yyw.moe>"]
repository = "https://github.com/Distributed-Network-Disk/Store-Node"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
websocket = "0.26.3"
